### ISSUE TITLE
Error in documentation maybe ? 

### ISSUE THREAD

**Issue by AgastyaK** [asgr/celestial#1]
Hello,

In celestial/man/dms2deg.Rd, line 16 (copied below)
`
The integer number of degrees you are converting. If it is not integer then the floor of the number is taken. This can contain the sign of the declination when sign='d', but must be all positive if the sign argument is specified (this is required if d contains any 0s, see below). If sign is specified, all d values should be 0<=d<=90, otherwise d values should be 0<=d<=90.
`
If no sign is specified, should it be 'otherwise d values should be -90<=d<=90 ?

Thank you

**Comment by asgr** [comment]
Yes, you are entirely correct! I will change the docs (the code does work correctly though).
